# Generated by Django 3.2 on 2021-12-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicemodel',
            name='intro_content',
            field=models.TextField(max_length=300),
        ),
    ]
