# Generated by Django 3.2 on 2021-12-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_alter_servicemodel_intro_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemodel',
            name='icon_class',
            field=models.CharField(default='..', max_length=200),
        ),
    ]
