# Generated by Django 3.2 on 2021-12-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_servicemodel_icon_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleDataForPdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=300)),
                ('company', models.CharField(max_length=300)),
                ('jobTitle', models.CharField(max_length=300)),
                ('message', models.TextField()),
            ],
        ),
    ]
