# Generated by Django 3.2 on 2021-12-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_researchinsight_paragraph_researchinsightinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchinsightinfo',
            name='intro_content',
            field=models.TextField(default='..'),
        ),
    ]
