# Generated by Django 3.2 on 2021-12-14 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_researchinsightinfo_intro_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchinsightinfo',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to='researcch_and_insight'),
        ),
    ]
