# Generated by Django 3.2 on 2021-12-16 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_peopledataforpdf_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peopledataforpdf',
            name='location',
            field=models.CharField(default='', max_length=600),
        ),
    ]
