# Generated by Django 3.2 on 2021-12-16 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_alter_peopledataforpdf_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peopledataforpdf',
            name='location',
            field=models.CharField(max_length=300),
        ),
    ]
